### ISSUE TITLE
 Error scraping user page ( docker behind reverse proxy)

### ISSUE THREAD

**Issue by PieterHollevoet** [YegorShtonda/strapi-plugin-instagram-feed#2]
Getting the following error when using strapi in docker with a reserve proxy (traefik)

Error: Error scraping user page "instagram_username"
    at Request._callback (/my-path/node_modules/instagram-scraping/index.js:43:24)
    at Request.self.callback (/my-path/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/my-path/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/my-path/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by PieterHollevoet** [comment]
Also tried on deployment with Heroku, same error.
