### ISSUE TITLE
Working plugin ?

### ISSUE THREAD

**Issue by BenoitEirik** [YegorShtonda/strapi-plugin-instagram-feed#9]
Does the plugin still work? I don't get anything in Instagram_feeds.
I just changed username in plugin.js to mine.

**Comment by BenoitEirik** [comment]
I got this error :
`Error: Error scraping user page "my_insta"
    at \node_modules\instagram-scraping\index.js:46:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
From previous event:
    at Object.exports.scrapeUserPage (\node_modules\instagram-scraping\index.js:12:12)
    at Object.fetchInstagramFeed (\node_modules\strapi-plugin-instagram-feed\services\instagram-feed.js:7:28)
    at Object.getInstagramFeed (\node_modules\strapi-plugin-instagram-feed\services\instagram-feed.js:91:73)
    at async Object.index (\node_modules\strapi-plugin-instagram-feed\controllers\instagram-feed.js:3:18)
    at async \node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:79:22
    at async module.exports (\node_modules\strapi-plugin-users-permissions\config\policies\permissions.js:88:3)
    at async \node_modules\strapi-utils\lib\policy.js:68:5
    at async \node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async \node_modules\strapi\lib\middlewares\xss\index.js:26:9
[2021-07-14T20:28:12.693Z] error TypeError: Assignment to constant variable.
    at Object.getInstagramFeed (\node_modules\strapi-plugin-instagram-feed\services\instagram-feed.js:92:12)
    at async Object.index (\node_modules\strapi-plugin-instagram-feed\controllers\instagram-feed.js:3:18)
    at async \node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:79:22
    at async module.exports (\node_modules\strapi-plugin-users-permissions\config\policies\permissions.js:88:3)
    at async \node_modules\strapi-utils\lib\policy.js:68:5
    at async \node_modules\strapi\lib\middlewares\parser\index.js:48:23
    at async \node_modules\strapi\lib\middlewares\xss\index.js:26:9`

**Comment by WardenCommander** [comment]
I would suggest you build it yourself from beginning. there are some mistypes as original library was updated.

**Comment by YegorShtonda** [comment]
Please, if you fix the plugin make a pool request.
